### ISSUE TITLE
XKCD Parser - If a number is passed in, it should query that specific number

### ISSUE THREAD

**Issue by chelming** [ServiceNowDevProgram/SlackerBot#245]
for whatever reason `!xkcd 2834` returned https://xkcd.com/283/ as a result and left off the 4. The 4 was important!

**Comment by ajcooper72** [comment]
I've got an update which I'll submit which follows these rules;

// if no parameters, display latest
// if number, display that number if valid otherwise random
// if -random then find a random
// anything else, do a search and display one of the results

**Comment by Lacah** [comment]
@ajcooper72 I've assigned it to you in attempt to avoid future conflicts. Let me know if you're not happy with it 😊

**Comment by earlduque** [comment]
works: 
- display latest
- if number display that
- if -random display random

doesn't work:
- search seems super weak now. `!xkcd exploits of a mom` and `!xkcd exploits` fail completely and do not return anything

**Comment by ajcooper72** [comment]
I'll have a look!

**Comment by ajcooper72** [comment]
@earlduque there's an issue with the terms not been encoded in the URI which I can fix.  

As for the quality of the search results, explainxkcd returns two sets of results, page title and page text.  Page text, especially when you introduce words like 'of' become quite random.  We could just take the page title results and randomise those?

**Comment by earlduque** [comment]
I'm down for whatever peeps think best lol ¯\_(ツ)_/¯

**Comment by ajcooper72** [comment]
The latest release 'fixes' the search results for random.  Given a search term, it removes any insignificant words (if, on, an etc) and them performs the search.  The results found in Page Title are prioritised over Page Text.  This is not a perfect solution, but fixes the use cases put forward across the various issues raised.

As this issue was regarding pulling the comic number, I would consider this issue closed.
